### ISSUE TITLE
Version control (semver)

### ISSUE THREAD

**Issue by blokhin** [mpds-io/visavis#11]
I can see `"version": "0.0.1"` in `mpds/visavis/-/package.json` and no other version mentions.

How do I specify a new version?

**Comment by nin-jin** [comment]
The version increases automatically based on the version in npm. But if necessary, it can also be set manually by creating package.json. The npm package name and other fields can be overrided in a similar way.

**Comment by blokhin** [comment]
As far as I understand, the current `$mol` approach to versioning is as follows:

- only patch version is getting automatically incremented **at the npm**
- any version bumps (including patch version) in the repository should be done manually
