### ISSUE TITLE
Packing into single-file bundle

### ISSUE THREAD

**Issue by blokhin** [mpds-io/visavis#12]
A single file with everything inside is incredibly convenient. Would that be supported by `$mol`?

**Comment by nin-jin** [comment]
All you need is `-/web.js` bundle. That contains all styles and scripts.

**Comment by blokhin** [comment]
@nin-jin yes, but I mean a standalone implementation (called `app`), not a widget (called `plot`). Please, have a look, how it is done for https://github.com/tilde-lab/optimade.science or https://github.com/basf/metis-gui using Svelte. No matter how complex the SPA is, it's always just a single `index.html` loadable literally from everywhere (even from a USB-stick!). Cool, eh?

**Comment by nin-jin** [comment]
index.html+web.js тоже может быть загружен ото всюду. Вот локализация не подгружается, да, но она тут и не нужна.
@stan-donarise выпилишь локализацию?

**Comment by stan-donarise** [comment]
а с json examples будем что-то делать, они нужны?

**Comment by stan-donarise** [comment]
> @stan-donarise ты про примеры форматов в `visavis/examples`? Конечно, они нужны.

Для того чтобы в этой ситуации работали сборщики (rollup и т.д.) надо поменять динамическую ленивую загрузку json файлов на статический импорт.. в моле такого вроде нет и делать такое мало смысла.

Самое простое решение вместо json файлов сделать cjs модули (`module.exports = {...}`), и тогда они будут включаться в бандл

**Comment by stan-donarise** [comment]
а вообще еще лучше тогда каждый график-пример переделать в mam-модуль (ts-файл с одной переменной-объектом)

**Comment by blokhin** [comment]
> а вообще еще лучше тогда каждый график-пример переделать в mam-модуль (ts-файл с одной переменной-объектом)

нет, так, к сожалению, не выйдет, т.к. источник данных внешний + JSON-формат вообще очень популярен

**Comment by stan-donarise** [comment]
т.е. останавливаемся на том, что примеры в такой бандл включать не надо? (пользователь сам загружает файлы-примеры)
